CREATE TABLE tasks(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  notes VARCHAR(100),
  created DATETIME NOT NULL,
  updated TIMESTAMP NOT NULL,
  active INT DEFAULT 1 NOT NULL,
  PRIMARY KEY (id)
);
